import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { gql, useQuery } from "@apollo/client";

const QUERY = gql`
  query {
    allUsers {
      email
      id
      name
    }
  }
`;


export default function Home() {
  const { data, loading, error } = useQuery(QUERY);

  console.log(data);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}
