export enum Violation {
  SPAM = "SPAM",
  HARRASMENT = "HARRASMENT",
  ADULTCONTENT = "ADULTCONTENT",
  PLAGIARISM = "PLAGIARISM",
  SCAM = "SCAM",
  FAKE = "FAKE",
  SOMETHINGELSE = "SOMETHINGELSE",
}